### ISSUE TITLE
Conversion from/to Record Types "cannot invoke a non-delegate type" error

### ISSUE THREAD

**Issue by sinanyildiz** [eswann/Mapster#110]
class Person {
    public string Name { get; }
    public int Age { get; }

    public Person(string name, int age) {
        this.Name = name;
        this.Age = age;
    }
}

var src = new { Name = "Mapster", Age = 3 };
var target = src.Adapt<Person>();

**Comment by eulercamposbarros** [comment]
```
class Person
{
    public string Name { get; }
    public int Age { get; }

    public Person(string name, int age) {
        this.Name = name;
        this.Age = age;
    }
}

var src = new { Name = "Mapster", Age = 3 };
var target = src.BuildAdapter().AdaptToType<Person>();
```

**Comment by qstarin** [comment]
I get the same error trying to run the example directly from the wiki:

```
void Main()
{
	var src = new { Name = "Mapster", Age = 3 };
	var target = src.Adapt<Person>();
}

class Person
{
	public string Name { get; }
	public int Age { get; }

	public Person(string name, int age) {
        this.Name = name;
        this.Age = age;
    }
}

```

Throws a RuntimBinderException
Message: Cannot invoke a non-delegate type
Target Site: System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)
HResult: -2146233088
Stack Trace:
at CallSite.Target(Closure , CallSite , Object , Object )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I have another example I am trying. If I uncomment the no-argument constructor I get the same exception as above. If I comment out the no-argument constructor I get a different exception:

```
void Main()
{
	var o1 = new { Id = 3, Name = "First", IsOn = false };
	var m1 = o1.Adapt<MyClass>();
}

public class MyClass
{
	//public MyClass() { }
	public MyClass(int id, string name, bool isOn) {
		Id = id;
		Name = name;
		IsOn = isOn;
	}
	
	public int Id { get; set; }
	public string Name { get; set; }
	public bool IsOn { get; set; }
}

```

Throws: CompileException
Message: Error while compiling
source=<>f__AnonymousType0`3[System.Int32,System.String,System.Boolean]
destination=UserQuery+MyClass
type=Map
Target Site: TypeAdapterConfig.CreateMapExpression (CompileArgument arg)
HResult: -2146233079
Inner Exception: ArgumentException - Type 'UserQuery+MyClass' does not have a default constructor
Stack Trace:
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapFunction(TypeTuple tuple)
   at Mapster.TypeAdapterConfig.AddToHash(Hashtable hash, TypeTuple key, Func`2 func)
   at Mapster.TypeAdapterConfig.GetMapFunction(Type sourceType, Type destinationType)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by chaowlert** [comment]
Problem is source type is anonymous type, which doesn't support with `src.Adapt<DestType>()` method. As @eulercamposbarros suggested pls use `src.BuildAdapter().AdaptToType<DestType>()` for now.

**Comment by qstarin** [comment]
Thank you. My bad for missing the difference in his example.
