### ISSUE TITLE
Please add support for DateTimeOffset

### ISSUE THREAD

**Issue by seanlinxs** [eswann/Mapster#8]
Trying to map DateTimeOffset gives:

Code:
```C#
DateTimeOffset dto1 = DateTimeOffset.UtcNow;
DateTimeOffset dto2 = TypeAdapter.Adapt<DateTimeOffset>(dto1);
```

Output
```C#
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: con
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, ConstructorInfo con)
   at Mapster.Utils.FastObjectFactory.CreateObjectFactory[T](Func`1 factory) in c:\Projects\Mapster\src\Mapster\Utils\FastObjectFactory.cs:line 27
   at Mapster.Adapters.ClassAdapter`2.get_DestinationFactory() in c:\Projects\Mapster\src\Mapster\Adapters\ClassAdapter.cs:line 37
   at Mapster.Adapters.ClassAdapter`2.Adapt(TSource source) in c:\Projects\Mapster\src\Mapster\Adapters\ClassAdapter.cs:line 51
   at (Object , Object[] )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source) in c:\Projects\Mapster\src\Mapster\TypeAdapter.cs:line 22
   at Expressions.Program.Main(String[] args) in c:\Users\Tilt\Documents\Visual Studio 2013\Projects\Expressions\Expressions\Program.cs:line 139
```

Thanks

**Comment by mhertis** [comment]
And also support for `TimeSpan` will be much appriciated.

**Comment by mhertis** [comment]
Should go thru code base first. It seems that manual registering primitive type does the trick. =D

```
TypeAdapterConfig.GlobalSettings.PrimitiveTypes.Add(typeof(DateTimeOffset));
TypeAdapterConfig.GlobalSettings.PrimitiveTypes.Add(typeof(TimeSpan));
```

**Comment by chaowlert** [comment]
Hi, Mapster 2.0 now automatically recognize immutable type like `DateTimeOffset` and `TimeSpan`.
